version: 2.1

jobs:
  build-webapp:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [react-template-build]
      - run:
          name: Build front-end
          command: |
            cd react-template
            npm run build
      - save_cache:
          paths: [react-template/node_modules]
          key: react-template-build

  
workflows:
  default:
    jobs:
      - build-webapp
